import type { LucideIcon } from "lucide-react";
import {
  Activity,
  Archive,
  ArchiveRestore,
  ArrowDown,
  ArrowDownLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUp,
  BadgeCheck,
  BookOpen,
  Bus,
  Calendar,
  Car,
  Cloud,
  CloudFog,
  CloudLightning,
  CloudRain,
  CloudSnow,
  CloudSun,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Compass,
  Copy,
  Download,
  Ellipsis,
  Eye,
  Globe,
  GripVertical,
  CreditCard,
  File,
  FileText,
  Headset,
  History,
  Hotel,
  House,
  IdCard,
  Image as ImageIcon,
  Inbox,
  Landmark,
  LayoutDashboard,
  LayoutGrid,
  ListChecks,
  Lock,
  LogOut,
  Mail,
  MapPin,
  Menu,
  Luggage,
  MessageCircle,
  MessagesSquare,
  Minus,
  Phone,
  Plane,
  PlaneTakeoff,
  Plus,
  Receipt,
  Search,
  Share2,
  ShieldCheck,
  Ship,
  Sparkles,
  Sun,
  Ticket,
  Timer,
  TrainFront,
  User,
  UserCog,
  UserPlus,
  Users,
  Wallet,
  Wrench,
  X,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  explore: Compass,
  luggage: Luggage,
  receipt_long: Receipt,
  badge: IdCard,
  chat: MessageCircle,
  timer: Timer,
  flight_takeoff: PlaneTakeoff,
  menu_book: BookOpen,
  arrow_forward: ArrowRight,
  task_alt: ListChecks,
  airlines: Plane,
  hotel: Hotel,
  airplane_ticket: Ticket,
  support_agent: Headset,
  history_edu: History,
  account_balance_wallet: Wallet,
  south_west: ArrowDownLeft,
  verified_user: ShieldCheck,
  verified: BadgeCheck,
  flight: Plane,
  description: FileText,
  picture_as_pdf: FileText,
  photo: ImageIcon,
  draft: File,
  download: Download,
  share: Share2,
  public: Globe,
  grid_view: LayoutGrid,
  group: Users,
  person_add: UserPlus,
  account_balance: Landmark,
  sync_alt: ArrowLeftRight,
  search: Search,
  person: User,
  credit_card: CreditCard,
  add: Plus,
  payments: Landmark,
  logout: LogOut,
  call: Phone,
  id_card: IdCard,
  health_and_safety: ShieldCheck,
  airport_shuttle: Bus,
  train: TrainFront,
  directions_car: Car,
  directions_boat: Ship,
  local_activity: Sparkles,
  event: Calendar,
  minus: Minus,
  close: X,
  expand_more: ChevronDown,
  mail: Mail,
  pin: MapPin,
  menu: Menu,
  build: Wrench,
  sun: Sun,
  cloud_sun: CloudSun,
  cloud: Cloud,
  fog: CloudFog,
  rain: CloudRain,
  snow: CloudSnow,
  storm: CloudLightning,
  // Menu agence (D-10, D-25) et poignées.
  dashboard: LayoutDashboard,
  shield_check: ShieldCheck,
  headset: Headset,
  lock: Lock,
  landmark: Landmark,
  forum: MessagesSquare,
  activity: Activity,
  eye: Eye,
  user_cog: UserCog,
  more_horiz: Ellipsis,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  home: House,
  inbox: Inbox,
  arrow_up: ArrowUp,
  arrow_down: ArrowDown,
  grip: GripVertical,
  content_copy: Copy,
  archive: Archive,
  unarchive: ArchiveRestore,
};

export function Icon({
  name,
  className,
  filled = false,
  strokeWidth,
}: {
  name: string;
  className?: string;
  filled?: boolean;
  strokeWidth?: number;
}) {
  const Cmp = ICONS[name] || File;
  return (
    <Cmp
      aria-hidden
      className={className}
      strokeWidth={strokeWidth ?? (filled ? 2.4 : 1.75)}
    />
  );
}
